# Generated by Django 5.0.6 on 2024-06-08 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='class_id',
            fields=[
                ('title', models.CharField(max_length=40, null=True)),
                ('number', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=150, null=True)),
                ('date', models.CharField(default='', max_length=20, null=True)),
                ('user', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_id',
            fields=[
                ('number', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
