# Generated by Django 5.0.6 on 2024-06-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_class_id_user_alter_teacher_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_id',
            name='user',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
